Minimal CSS Question Components
InVisionAR/web-frontend pull request #16
Opened 2020-09-16 16:07 UTC by rarchitgupta

2020-09-16 23:00 UTC, arnavb requested changes
Make sure to use bulma styling for containers, etc. Position related styling should be minimal, the bulma defaults are good to follow. Be a little more consistent with classnames (use dash case everywhere, I notice camelCase in some places). 

Also, could you make an example component with some sample questions as a page? That way I can see what it looks like in practice.

2020-09-17 03:04 UTC, rarchitgupta commented
Alright I'll see to it

2020-09-17 06:02 UTC, rarchitgupta commented
I added a quiz page you can visit by manually adding "/quiz" into the URL. Didn't mess with the navbar. There's an array of question objects you can change to view the questions. Also used Bulma and changed classnames

2020-09-17 21:48 UTC, arnavb requested changes

2020-09-17 21:48 UTC, arnavb commented on .prettierrc
> +{}
Delete this file.

2020-09-17 21:48 UTC, arnavb commented on src/pages/quiz.css
> +body {
Don't set global styles, this will propagate across all pages since we're dealing with a single page app.

2020-09-17 21:48 UTC, arnavb commented on src/pages/quiz.js
> +    <div className="container">
Regarding answers, I think radio choices stacked vertically would be better. In addition, I think you should use the Bulma form controls for input related things. There's lots of quiz apps for inspiration, such as:

![image](https://user-images.githubusercontent.com/30810402/93531882-f182e580-f90d-11ea-8984-cc42a94408f2.png)

or something simpler:

![image](https://user-images.githubusercontent.com/30810402/93531916-fe9fd480-f90d-11ea-89db-017b29cf74b6.png)

2020-09-18 02:43 UTC, rarchitgupta commented
Yeah sorry I didn't mean to push the prettier config. I'll look into the rest too.

2020-09-18 04:10 UTC, rarchitgupta commented
I can't figure out what's causing the blank space below the last question. Rest everything I think I've taken care of

2020-09-21 22:59 UTC, arnavb approved these changes

2020-09-21 22:59 UTC, merged