Added hook for ham menu functionality
InVisionAR/web-frontend pull request #19
Opened 2020-09-22 15:17 UTC by asharonbaltazar

The menu is implemented with toggle functionality and works as expected. No need for custom JS — possible with a `useState` hook

2020-09-22 23:07 UTC, arnavb requested changes
Functionality-wise, this seems good. Could you also address the other part of the issue, the CSS transition for the dropdown?

2020-09-22 23:12 UTC, asharonbaltazar commented
Sure. Any particular way you'd like me to achieve that?

2020-09-23 16:34 UTC, arnavb commented
I think adding a CSS transition to the active class would be the best approach. This [issue](https://github.com/jgthms/bulma/issues/1790) has some examples.

2020-09-23 19:44 UTC, asharonbaltazar commented
I think CSS is too messy, IMO, especially with a pre-existing library. React has plenty of animation libraries, though. 

I'll just stop here. You can either accept my PR or just close it. Sorry about that.

2020-09-24 02:11 UTC, arnavb requested changes
As far as CSS transition goes, it really isn't going to bloat anything since it's just simple code to add (I wrote the code below by tweaking the code from that issue a little bit). Try doing something similar and adding it. In contrast to what you said, a React transition library will add _much_ more bloat than just 2 CSS rule blocks.

```CSS
.navbar-menu {
  display: block;
  opacity: 0;

  position: absolute;
  left: 0;
  right: 0;

  transform: translateY(-100%);
  transition: all 0.2s cubic-bezier(0.3, 0.01, 1, -0.09);
  pointer-events: none;
}

.navbar-menu.is-active {
  opacity: 1;
  transform: none;
  pointer-events: auto;
}
```

2020-09-24 02:11 UTC, arnavb commented on src/App.js
> +            onClick={() => setOpen(!open)}
The button also needs the `is-active` class after the toggle.

2020-09-24 20:03 UTC, arnavb approved these changes
Even though the transition itself is incomplete, I'm merging this in because someone else will work on getting that set up.

2020-09-24 20:03 UTC, merged