[WIP] Landing page prototype
InVisionAR/web-frontend pull request #3
Opened 2020-09-06 17:21 UTC by arnavb

This is only a design prototype, not final.

#2.

Issues at the moment:
- [ ] Bulma fullheight hero + navbar is slightly taller than the viewport. Needs to be verified.
- [ ] Landing page info is still missing.

2020-09-07 02:06 UTC, sagarreddypatil commented
Why is build failing?

2020-09-07 02:07 UTC, sagarreddypatil commented on src/pages/home.js
> +            <p className="title">InvisionAR</p>
V should be capitalized like "InVisionAR"

2020-09-07 02:10 UTC, sagarreddypatil requested changes
Need to add the actual pages and fix failing ci build

2020-09-07 02:10 UTC, sagarreddypatil commented on package.json
> +    "node-sass": "^4.14.1",
Move to dev dependency

2020-09-07 02:10 UTC, sagarreddypatil commented on src/pages/home.js
> +            <p className="title">InvisionAR</p>
V should be capitalized

2020-09-08 03:20 UTC, sagarreddypatil commented
bulma has a fullheight hero. docs here: https://bulma.io/documentation/layout/hero/

2020-09-08 16:13 UTC, arnavb commented
@sagarreddypatil I fixed it. Don't forget we have a navbar also.

2020-09-12 19:19 UTC, arnavb commented
Superseded by #9, #10, and #11

2020-09-12 19:19 UTC, closed without merging